# Generated by Django 4.0 on 2021-12-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabinet', '0003_adres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='n_doma',
            field=models.SmallIntegerField(default='------', verbose_name='Номер дома № :'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='n_kvartiri',
            field=models.SmallIntegerField(default='------', verbose_name='Номер квартиры № :'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='n_podezda',
            field=models.SmallIntegerField(default='------', verbose_name='Номер подъезда № :'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='pochta_index',
            field=models.SmallIntegerField(default='------', verbose_name='Почтовый индекс'),
        ),
    ]
