# Generated by Django 4.0 on 2021-12-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabinet', '0004_alter_adres_n_doma_alter_adres_n_kvartiri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='gorod',
            field=models.CharField(default='Павловская', max_length=80, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='raion',
            field=models.CharField(default='Район', max_length=80, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='ulica',
            field=models.CharField(default='Улица', max_length=80, verbose_name='Улица'),
        ),
    ]
