# Generated by Django 4.0 on 2021-12-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabinet', '0005_alter_adres_gorod_alter_adres_raion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='---', max_length=128)),
                ('avatar', models.ImageField(height_field=50, upload_to='image/avatar/', verbose_name='Миниатюра', width_field=50)),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.AlterField(
            model_name='adres',
            name='data_start',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата подачи'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='data_stop',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата снятия'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='n_kvartiri',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Номер квартиры № :'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='n_podezda',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Номер подъезда № :'),
        ),
    ]
