# Generated by Django 4.0 on 2021-12-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabinet', '0009_remove_profile_avatar_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='image/avatar/', verbose_name='Миниатюра'),
        ),
    ]
