# Generated by Django 4.0 on 2021-12-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kabinet', '0012_rename_klient_profile_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
