# Generated by Django 4.0 on 2021-12-10 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kabinet', '0013_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Псевдоним')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='image/avatar/', verbose_name='Миниатюра')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kabinet.user')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
